# Generated by Django 5.2.8 on 2025-11-28 14:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_file',
            field=models.FileField(upload_to='music/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'aac', 'wav', 'flac', 'ogg', 'm4a'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='music',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.music'),
        ),
    ]
