# Generated by Django 5.2.8 on 2026-02-21 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_repost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='repost',
            new_name='reposts',
        ),
    ]
