# Generated by Django 5.2.8 on 2026-02-22 08:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_rename_repost_post_reposts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reposts',
            field=models.ManyToManyField(blank=True, null=True, related_name='reposted_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
