# Generated by Django 5.2.8 on 2026-02-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
