# Generated by Django 5.2.8 on 2026-03-08 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('gif', 'Gif'), ('reaction', 'Reaction')], default='text', max_length=10),
        ),
    ]
